import type { Metadata } from "next";
import "@/app/globals.css";
import HeaderNavBar from "@/app/view/main/header/header-nav-bar/HeaderNavBar";
import SimpleBottomNavigation from "@/app/view/main/bottom-nav/BottomNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <HeaderNavBar />
        {children}
        <SimpleBottomNavigation />
    </html>
  );
}
