export const dataset = [
  {
    london: 59,
    paris: 57,
    newYork: 86,
    seoul: 21,
    month: 'Jan',
    month1: '1',
    character: '병욱',
  },
  {
    london: 50,
    paris: 52,
    newYork: 78,
    seoul: 28,
    month: 'Feb',
    month1: '2',
    character: '종법',
  },
  {
    london: 47,
    paris: 53,
    newYork: 106,
    seoul: 41,
    month: 'Mar',
    month1: '3',
    character: '범수',
  },
  {
    london: 54,
    paris: 56,
    newYork: 92,
    seoul: 73,
    month: 'Apr',
    month1: '4',
    character: '득천',
  },
  {
    london: 57,
    paris: 69,
    newYork: 92,
    seoul: 99,
    month: 'May',
    month1: '5',
    character: '태령',
  },
  {
    london: 60,
    paris: 63,
    newYork: 103,
    seoul: 144,
    month: 'June',
    month1: '6',
    character: '현성',
  },
  {
    london: 59,
    paris: 60,
    newYork: 105,
    seoul: 800,
    month: 'July',
    month1: '7',
    character: '원석',
  },
  {
    london: 65,
    paris: 60,
    newYork: 106,
    seoul: 249,
    month: 'Aug',
    month1: '8',
    character: '지현',
  },
  {
    london: 51,
    paris: 51,
    newYork: 95,
    seoul: 131,
    month: 'Sept',
    month1: '9',
    character: '나영',
  },
  {
    london: 60,
    paris: 65,
    newYork: 97,
    seoul: 55,
    month: 'Oct',
    month1: '10',
    character: '혜지',
  },
  {
    london: 67,
    paris: 64,
    newYork: 76,
    seoul: 48,
    month: 'Nov',
    month1: '11',
    character: '다혜',
  },
  {
    london: 61,
    paris: 70,
    newYork: 103,
    seoul: 25,
    month: 'Dec',
    month1: '12',
    character: '열라긴이름임',
  },

  {
    london: 59,
    paris: 57,
    newYork: 86,
    seoul: 21,
    month: 'Jan',
    month1: '1',
    character: '1병욱',
  },
  {
    london: 50,
    paris: 52,
    newYork: 78,
    seoul: 28,
    month: 'Feb',
    month1: '2',
    character: '2종법',
  },
  {
    london: 47,
    paris: 53,
    newYork: 106,
    seoul: 41,
    month: 'Mar',
    month1: '3',
    character: '3범수',
  },
  {
    london: 54,
    paris: 56,
    newYork: 92,
    seoul: 73,
    month: 'Apr',
    month1: '4',
    character: '4득천',
  },
  {
    london: 57,
    paris: 69,
    newYork: 92,
    seoul: 99,
    month: 'May',
    month1: '5',
    character: '5태령',
  },
  {
    london: 60,
    paris: 63,
    newYork: 103,
    seoul: 144,
    month: 'June',
    month1: '6',
    character: '6현성',
  },
  {
    london: 59,
    paris: 60,
    newYork: 105,
    seoul: 800,
    month: 'July',
    month1: '7',
    character: '7원석',
  },
  {
    london: 65,
    paris: 60,
    newYork: 106,
    seoul: 249,
    month: 'Aug',
    month1: '8',
    character: '8지현',
  },
  {
    london: 51,
    paris: 51,
    newYork: 95,
    seoul: 131,
    month: 'Sept',
    month1: '9',
    character: '9나영',
  },
  {
    london: 60,
    paris: 65,
    newYork: 97,
    seoul: 55,
    month: 'Oct',
    month1: '10',
    character: '10혜지',
  },
  {
    london: 67,
    paris: 64,
    newYork: 76,
    seoul: 48,
    month: 'Nov',
    month1: '11',
    character: '11다혜',
  },
  {
    london: 61,
    paris: 70,
    newYork: 103,
    seoul: 25,
    month: 'Dec',
    month1: '12',
    character: '12열라긴이름',
  },
];

export function valueFormatter(value: number | null) {
  return `${value}mm`;
}
