export enum CharacterStyleType {
  Realistic, // "Realistic"
  Anime, // "Anime"
}

export enum CharacterGenderType {
  Girl, // "1girl, solo"
  Man, // "1man, solo"
  All, // "solo"
}

export enum CharacterRaceType {
  None, // ""
  Caucasian, // "caucasian"
  Asian, // "asian"
  Latina, // "caucasian"
  Arabic, // "Arabic"
  Black, // "black"
  Max,
}

export enum CharacterAgeType {
  None, // ""
  Teen, // "teenager"
  Twenty, // "20 years old"
  Thirty, // "30 years old"
}

export enum CharacterEyeColorType {
  None, // ""
  Brown, // "brown eyes"
  Blue, // "blue eyes"
  Green, // "green eyes"
  Yellow, // "yellow eyes"
  Red, // "red eyes"
}

export enum CharacterHairStyleType {
  None, // ""
  Straight, // "straight_hair"
  Braids, // "braid"
  Bangs, // "Blunt_bangs"
  Curly, // "curly_hair"
  Bun, // "hair_bun"
  Short, // "short_hair"
  Long, // "long_hair"
  Ponytail, // "ponytail"
  Twintails, // "short twintails"
  Max,
  BuzzCut, // "buzz cut"
  Long2, // "man long_hair"
  SlickedBack, // "hair slicked back"
  Dreadlocks, // "(man with dreadlocks)"
  Bald, // "bald"
}

export enum CharacterHairColorType {
  None, // ""
  Blonde, // "Blonde_hair"
  Brunette, // "brown_hair"
  Black, // "black_hair"
  Redhead, // "red_hair"
  Pink, // "pink_hair"
  White, // "white_hair"
  Blue, // "blue_hair"
  Green, // "green_hair"
  Purple, // "purple_hair"
}

export enum CharacterBodyType {
  None, // ""
  Petite, // "A petite"
  Slim, // "slender"
  Athletic, // "A strong"
  Voluptuous, // "Voluptuous"
  Curvy, // "chubby"
  Skinny, // "skinny"
  Muscular, // "(slender), muscular"
  Wide, // "Muscular man with broad shoulders, low body fat, defined muscles, ripped abs,"
}

export enum CharacterTopSizeType {
  None, // ""
  Flat, // "(A slim woman with a flat chest)"
  Small, // "(small_breasts)"
  Medium, // "(medium_breasts)"
  Large, // "(large_breasts), bra"
  Huge, // "(huge_breasts), bra"
}

export enum CharacterBottomSizeType {
  None, // ""
  Small, // "(small buttocks:0.5)"
  Medium, // "(well-proportioned buttocks:0.5)"
  Large, // "(huge ass:0.5), panties"
  Skinny, // "(modestly-sized buttocks:0.5)"
  Athletic, // "muscular buttocks"
}

export enum CharacterClothingType {
  None, // "pants"
  Skirt, // "crop top, micro_skirt"
  Cheerleader, // "cheerleader"
  PencilDress, // "body-hugging dress"
  LongDress, // "long_dress"
  WomanBasketballJersey, // "basketball_uniform"
  Soccer, // "soccer_uniform"
  Tennis, // "tennis_uniform"
  Swimsuit, // "one-piece_swimsuit"
  Sport, // "sweatpants"
  WeddingDress, // "wedding_dress"
  FancyDress, // "Sequined Dress"
  Witch, // "fantasy-inspired witch outfit, black top"
  Lingerie, // "luxurious lingerie"
  LatexOutfit, // "black_latex_dress"
  SchoolOutfit, // "school_uniform"
  YogaOutfit, // "yoga_outfit"
  LeatherOutfit, // "leather outfit, leather top"
  Corset, // "colored_corset"
  Angel, // "angel_costume, angel wings"
  Maid, // "maid"
  WomanMedievalArmor, // "medieval armor"
  LabCoat, // "white lab coat, shirt, skirt"
  Cowboy, // "cowgirl wearing a classic cowboy hat, leather jacket, denim jeans, boots"
  Carnival, // "A woman dressed in a traditional Brazilian festival costume, feathers, sequins, gemstones"
  Casual, // "casual_outfit"
  Nurse, // "(nurse:1.3)"
  SantaClaus, // "(santa_dress:1.3)"
  Police, // "modern police uniform"
  Steampunk, // "fantasy-style steampunk outfit"
  Superhero, // "superhero"
  Teacher, // "modern teacher attire, rectangular_eyewear"
  Viking, // "warrior, fantasy-inspired Viking outfit"
  Firefighter, // "A firefighter in specialized rescue gear, wearing a lighter"
  Military, // "modern military attire, wearing a tactical uniform"
  Construction, // "construction_worker, jacket, work pants"
  LongCoat, // "long_coat, turtleneck, skirt"
  Hoodie, // "print_hoodie, skirt"
  Jeans, // "jeans"
  Leggings, // "leggings designed for exercise, tube_top"
  Ninja, // "(ninja:1.3)"
  Pyjamas, // "(pajamas:1.3)"
  Clown, // "(woman dressed as a clown:1.2), wearing a colorful harlequin outfit"
  FlightAttendant, // "flight attendant uniform"
  Barista, // "A barista dressed in a classic coffee shop uniform"
  BellyDancer, // "A belly dancer in contemporary dancewear"
  Goth, // "(Gothic_outfit:1.3)"
  Pirate, // "(pirate:1.3)"
  Prisoner, // "A woman wearing a prison jumpsuit designed for female inmates"
  RaceDriver, // "colored_racing_suit"
  Hijab, // "A woman dressed in casual hijab attire, wearing a comfortable"
  Tutu, // "tutu"
  Poncho, // "(poncho raincoat:1.3)"
  Hiphop, // "hip-hop fashion, wearing oversized, distressed denim, a graphic t-shirt with bold prints, snapback cap"
  Skatepark, // "skate park, colorful graphic t-shirt, denim_shorts"
  Lumberjack, // "(lumberjack:1.3), overall"
  Adventurer, // "Long-sleeve shirt, cargo pants, wide-brimmed hat, utility vest"
  Sailor, // "sailor_(naval_uniform)"
  Golf, // "golf_uniform"
  Onesie, // "(onesie:1.4)"
  OversizedShirt, // "(oversized shirt:1.2), loose fit, rolled-up sleeves"
  Tribal, // "(Tribal clothing:1.6), natural fabrics"
  Secretary, // "Secretary outfit, fitted blouse, pencil skirt, high heels"
  PopStar, // "Pop star outfit, flashy colors, sequined jacket, stylish crop top"
  BusinessSuit, // "business_suit, shirt"
  JeansTShirt, // "jeans,t-shirt"
  Chino, // "chino_pants"
  BermudaPolo, // "bermuda shorts"
  SweaterPants, // "sweater"
  TrackSuit, // "track suit"
  Blazer, // "blazer"
  LeatherJacket, // "leather jacket"
  HoodiePants, // "hoodie, pants"
  DenimJacket, // "denim jacket"
  Cardigan, // "cardigan"
  PeaCoat, // "pea_coat"
  SleevesDress, // "long sleevesdress_shirt, vest"
  HenryNeck, // "henry neck shirt, shorts"
  Trench, // "trench"
  Jacket, // "jacket"
  LinenPants, // "linen_pants"
  CorduroyPants, // "corduroy_pants"
  HenleyShort, // "henley, short"
  PrincessDress, // "princess dress"
  JoogersPants, // "joggers_pants"
  Bikini, // "bikini"
}
